[package]
name = "point-nd"
version = "0.2.0"
edition = "2021"

description = "A simple and flexible data structure for modelling points on an axis"

repository = "https://github.com/taennan/point-nd/tree/main"

authors = [
    "Taennan taennan@zohomail.com"
]

exclude = [".idea", ".gitignore"]

license = "MIT"

keywords = ["point", "geometry", "multidimensional", "axes", "axis"]
categories = ["data-structures"]